In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import LabelEncoder

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
df = pd.DataFrame([['green','M',10.1,'class1'],
                 ['red','L',13.5,'class2'],
                 ['blue','XL',15.3,'class1']])

In [5]:
df.columns = ['color','size','price','classlabel']

In [6]:
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

# 有序特征的映射

In [7]:
size_mapping = {'XL':3,'L':2,'M':1}

In [8]:
ds = df['size'] 

In [9]:
df['size'] = df['size'].map(size_mapping) #将尺码映射成数字

In [10]:
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [11]:
inv_size_mapping={v:k for k,v in size_mapping.items()} #同上操作将尺码逆映射回来

In [12]:
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

# 类标的编码

np.unique(Series) 返回Series去重后的ndarray格式

In [13]:
def classMapping(df):
    """映射方法同有序数列映射"""
    class_mapping = {label:idx for idx,label in enumerate(np.unique(df['classlabel']))}
    df['classlabel'] = df['classlabel'].map(class_mapping)
    inv_class_mapping = {v:k for k,v in class_mapping.items()}#逆映射同有序数列逆映射
    return df

In [15]:
class_le = LabelEncoder()

In [19]:
y = class_le.fit_transform(df['classlabel'].values) #效果同上述函数

In [20]:
 class_le.inverse_transform(df['classlabel'].values)#逆映射方法

array([0, 1, 0])

# 标称特征上的独热编码

In [27]:
X = df[['color','size','price']].values

In [30]:
color_le = LabelEncoder()

In [32]:
X[:,0]=color_le.fit_transform(X[:,0])

In [33]:
X

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [34]:
ohe = OneHotEncoder(categorical_features=[0])

In [35]:
ohe.fit_transform(X).toarray()

/Users/fannian/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/fannian/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])

In [36]:
pd.get_dummies(df[['color','size','price']])#pandas实现独热编码技术中的虚拟特征

size  price  color_blue  color_green  color_red
0     1   10.1           0            1          0
1     2   13.5           0            0          1
2     3   15.3           1            0          0